import 'dart:async';
import 'dart:io';
import 'dart:convert';
import 'package:path/path.dart' as path;
import '../../utils/constants.dart';
import '../../utils/logger.dart';
import 'sdk_manager.dart';

/// Gradle包装器
class GradleWrapper {
  static final GradleWrapper _instance = GradleWrapper._internal();
  factory GradleWrapper() => _instance;
  GradleWrapper._internal();

  String? _projectPath;
  final _outputController = StreamController<GradleOutput>.broadcast();
  bool _initialized = false;

  /// 初始化
  Future<void> init(String projectPath) async {
    _projectPath = projectPath;
    await _ensureWrapper();
    _initialized = true;
    logger.i(LogTags.build, 'GradleWrapper initialized for: $projectPath');
  }

  /// 确保Gradle Wrapper存在
  Future<void> _ensureWrapper() async {
    if (_projectPath == null) return;

    final gradlew = _getWrapperScript();
    final wrapperDir = Directory(path.join(_projectPath!, 'gradle', 'wrapper'));

    // 检查wrapper.properties
    final propsFile = File(path.join(wrapperDir.path, 'gradle-wrapper.properties'));
    if (!await propsFile.exists()) {
      await wrapperDir.create(recursive: true);
      
      // 创建默认的wrapper配置
      await propsFile.writeAsString('''distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.2-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
''');
    }

    // 创建gradlew脚本
    if (!File(gradlew).existsSync()) {
      await _createGradlewScript(gradlew);
    }

    // 创建gradlew.bat (Windows)
    if (Platform.isWindows) {
      final gradlewBat = '${gradlew}w.bat';
      await _createGradlewBatScript(gradlewBat);
    }
  }

  String _getWrapperScript() {
    return path.join(_projectPath ?? '', Platform.isWindows ? 'gradlew.bat' : 'gradlew');
  }

  /// 创建Unix gradlew脚本
  Future<void> _createGradlewScript(String gradlewPath) async {
    const script = '''#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Add default JVM options here.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support.
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )          darwin=true  ;; #(
  MSYS* | MINGW* )   msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=\$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "\$JAVA_HOME" ] ; then
    if [ -x "\$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="\$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="\$JAVA_HOME/bin/java"
    fi
    if [ ! -x "\$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: \$JAVA_HOME"
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Increase the maximum file descriptors if we can.
if ! "\$cygwin" && ! "\$darwin" && ! "\$nonstop" ; then
    case \$MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case \$MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "\$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to \$MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order
set -- \
        "-Dorg.gradle.appname=\$(basename "\$0")" \
        -classpath "\$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "\$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
eval "set -- \$(
        printf '%s\n' "\$DEFAULT_JVM_OPTS \$JAVA_OPTS \$GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "\$JAVACMD" "\$@"
''';

    await File(gradlewPath).writeAsString(script);
    await Process.run('chmod', ['+x', gradlewPath]);
  }

  /// 创建Windows gradlew.bat脚本
  Future<void> _createGradlewBatScript(String gradlewBatPath) async {
    const script = '''@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@if "%DEBUG%"=="" @echo off
@rem Setup for Windows

setlocal enabledelayedexpansion

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% equ 0 goto execute

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
goto fail

:execute
@rem Setup the command line
set JDK_ARGS="-Xmx64m" "-Xms64m"

@rem Execute Gradle
"%JAVA_EXE%" %JDK_ARGS% -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

:end
@rem End local scope for the variables with windows NT shell
if %ERRORLEVEL% equ 0 goto mainEnd

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
if %EXIT_CODE% equ 0 set EXIT_CODE=1
set EXIT_CODE=%ERRORLEVEL%
if %EXIT_CODE% equ 0 set EXIT_CODE=1

exit /b %EXIT_CODE%

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega
''';

    await File(gradlewBatPath).writeAsString(script);
  }

  /// 执行Gradle任务
  Future<GradleResult> execute(
    String task, {
    List<String> args = const [],
    bool verbose = false,
  }) async {
    if (!_initialized || _projectPath == null) {
      throw StateError('GradleWrapper not initialized');
    }

    final gradlew = _getWrapperScript();
    final allArgs = [task, ...args];
    if (verbose) {
      allArgs.add('--info');
    }

    logger.i(LogTags.build, 'Executing Gradle: $task');

    try {
      final process = await Process.start(
        gradlew,
        allArgs,
        workingDirectory: _projectPath,
        environment: {
          'ANDROID_HOME': sdkManager.getAndroidSdkPath() ?? '',
          'JAVA_HOME': path.dirname(path.dirname(sdkManager.getJavaPath() ?? '')),
        },
      );

      final stdoutBuffer = StringBuffer();
      final stderrBuffer = StringBuffer();

      process.stdout.transform(utf8.decoder).listen((data) {
        stdoutBuffer.write(data);
        _outputController.add(GradleOutput(
          type: GradleOutputType.stdout,
          text: data,
          timestamp: DateTime.now(),
        ));
      });

      process.stderr.transform(utf8.decoder).listen((data) {
        stderrBuffer.write(data);
        _outputController.add(GradleOutput(
          type: GradleOutputType.stderr,
          text: data,
          timestamp: DateTime.now(),
        ));
      });

      final exitCode = await process.exitCode;

      return GradleResult(
        success: exitCode == 0,
        exitCode: exitCode,
        stdout: stdoutBuffer.toString(),
        stderr: stderrBuffer.toString(),
      );
    } catch (e) {
      logger.e(LogTags.build, 'Gradle execution failed', error: e);
      return GradleResult(
        success: false,
        exitCode: -1,
        stderr: e.toString(),
      );
    }
  }

  /// 获取Gradle版本
  Future<String?> getVersion() async {
    final result = await execute('--version');
    if (result.success) {
      final match = RegExp(r'Gradle (\d+\.\d+(?:\.\d+)?)').firstMatch(result.stdout);
      return match?.group(1);
    }
    return null;
  }

  /// 任务列表流
  Stream<GradleOutput> get outputStream => _outputController.stream;

  void dispose() {
    _outputController.close();
  }
}

/// Gradle输出
class GradleOutput {
  final GradleOutputType type;
  final String text;
  final DateTime timestamp;

  const GradleOutput({
    required this.type,
    required this.text,
    required this.timestamp,
  });
}

enum GradleOutputType { stdout, stderr, info, error }

/// Gradle执行结果
class GradleResult {
  final bool success;
  final int exitCode;
  final String stdout;
  final String stderr;

  const GradleResult({
    required this.success,
    required this.exitCode,
    required this.stdout,
    required this.stderr,
  });
}

/// 全局Gradle包装器实例
final gradleWrapper = GradleWrapper();
